#!/bin/bash

#SBATCH --ntasks=16
#SBATCH --nodes=1
# SBATCH --mem=243200
#SBATCH --partition=highmem
#SBATCH --job-name=ResolventAnalysis
#SBATCH --time=60:00:00
#SBATCH --output=P-PLOT.out
# SBATCH --exclusive
# SBATCH --exclude=ruby035,ruby036,ruby037
# SBATCH --dependency=afterok:1908224

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

module purge
module load texlive
module load conda
source activate an

# cd data
# ./lotus-npy.sh "0.005/128"
# cd ..
# python resolvent/run_resolvent.py "0.005/128"
# python resolvent/run_resolvent.py "0.001/32"
# python resolvent/run_resolvent.py "0.001/64"
# python resolvent/run_resolvent.py "0.001/128"
# python resolvent/run_resolvent.py "0.001/16"
python resolvent/run_resolvent.py "test/up"

# python resolvent/plot_field.py "test/up"
# python resolvent/plot_field.py "0.001/128"
# python resolvent/plot_field.py "0.001/16"

# python resolvent/plot_peaks.py "0.001/32"
# python resolvent/plot_peaks.py "0.001/16"
# python resolvent/plot_peaks.py "0.001/64"
# python resolvent/plot_peaks.py "0.001/128"
python resolvent/plot_peaks.py "test/up"

# python resolvent/load_data.py
# python resolvent/run_resolvent.py 
