#!/bin/bash

#SBATCH --ntasks=64
#SBATCH --nodes=1
# SBATCH --mem=243200
#SBATCH --partition=highmem
#SBATCH --job-name=ResolventAnalysis
#SBATCH --time=60:00:00
#SBATCH --output=RA.out
# SBATCH --exclusive
# SBATCH --exclude=ruby035,ruby036,ruby037
# SBATCH --dependency=afterok:1908224

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

module purge
module load texlive
module load conda
source activate an

python resolvent/run_resolvent.py "128/0.001"
