#!/bin/bash
#SBATCH --ntasks=64
#SBATCH --nodes=1
# SBATCH --mem=243200
#SBATCH --partition=highmem
#SBATCH --job-name=interactive
#SBATCH --time=18:00:00
#SBATCH --output=SLEEP.out
# SBATCH --exclusive
# SBATCH --exclude=ruby035,ruby036,ruby037
# SBATCH --dependency=afterok:1908224

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

module purge
module load conda
source activate an

# python resolvent/SVD_save.py
sleep 720000
