#!/bin/bash
#SBATCH --ntasks=64
#SBATCH --nodes=1
# SBATCH --mem=243200
#SBATCH --partition=highmem
#SBATCH --job-name=DMD
#SBATCH --time=20:00:00
#SBATCH --output=INTERACTIVE.out
# SBATCH --exclusive
# SBATCH --exclude=ruby035,ruby036,ruby037
# SBATCH --dependency=afterok:1908224

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

module purge
module load conda
source activate an
module load texlive
# module load openmpi/4.0.5/amd
# module load openmpi/4.1.4/gcc
# module load mpich/3.2.1/gcc
# module load hdf5/1.12.2/intel-mpi

# cd data/swimming
# python bmask.py
# python collect_save.py
# cd ../..
# python src/DMD-RA-working.py
# cd data/0/uvp
# python save_h5.py
sleep 720000
