#!/bin/bash
#SBATCH --ntasks=6
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=6
#SBATCH --partition=highmem
#SBATCH --job-name=interactive
#SBATCH --time=6:00:00

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

# module load conda
# source activate an

# python resolvent/SVD_save.py
sleep 720000
