#!/bin/bash

#SBATCH --ntasks=1024
#SBATCH --nodes=16
#SBATCH --partition=amd
#SBATCH --job-name=sp16
#SBATCH --time=10:00:00

LAM=16

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

module load openmpi/4.0.5/amd
module load conda
source activate rlotus

python run-rough.py $LAM
# cd ../..
# ./lotus-npy.sh "0.001/$LAM"

