#!/bin/bash

#SBATCH --ntasks=1024
#SBATCH --nodes=16
#SBATCH --partition=amd
#SBATCH --job-name=restart_runs
#SBATCH --time=60:00:00
#SBATCH --output=JOB.out
# SBATCH --exclude=ruby035,ruby036,ruby037
# SBATCH --dependency=afterok:1908224

LAM=32

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

module purge
module load openmpi/4.0.5/amd
module load conda
source activate an

python run-rough.py $LAM
cd ../..
./lotus-npy.sh "0.005/$LAM"
cd ..
python resolvent/run_resolvent.py "0.005/$LAM"

