#!/bin/bash

#SBATCH --ntasks=1024
#SBATCH --nodes=16
#SBATCH --partition=amd
#SBATCH --job-name=sp-128
#SBATCH --time=10:00:00

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

# module purge
module load openmpi/4.0.5/amd
module load conda
source activate rlotus

python run-rough.py
# cd ../../..
# python data/watch_simdir.py
# python data/bmask.py
# python data/collect_save.py