#!/bin/bash

#SBATCH --ntasks=1024
#SBATCH --nodes=16
#SBATCH --partition=amd
#SBATCH --job-name=fbb
#SBATCH --time=60:00:00
#SBATCH --output=JOB.out
# SBATCH --exclude=ruby035,ruby036,ruby037
# SBATCH --dependency=afterok:1908224

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

module purge
module load openmpi/4.0.5/amd
module load conda
source activate an

python run-rough.py

