#!/bin/bash
#SBATCH --ntasks=1024
#SBATCH --nodes=16
#SBATCH --ntasks-per-node=64
#SBATCH --partition=amd
#SBATCH --job-name=smooth-128
#SBATCH --time=24:00:00

echo "Starting calculation at $(date)"
echo "---------------------------------------------------------------"

# module purge
module load openmpi/4.0.5/amd
module load conda
source activate rlotus

python run-2d.py

cd ../..
./lotus-npy.sh "test/span64"
# cd ..
# python resolvent/run_resolvent.py "0.001/$LAM"


